# Generated by Django 4.2 on 2023-06-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default2.jpg', upload_to='user_profile_pics'),
        ),
    ]
