# Generated by Django 4.0.4 on 2023-06-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeType',
            new_name='PropertyTpe',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertytpe',
            options={'verbose_name_plural': 'Home Types'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'States'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='home_type',
            new_name='type',
        ),
    ]
