# Generated by Django 4.2.2 on 2023-06-13 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_hometype_propertytpe_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertytpe',
            options={'verbose_name_plural': 'Property Types'},
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
