# Generated by Django 4.2.2 on 2023-07-21 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='home_page_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.uploadedimage'),
            preserve_default=False,
        ),
    ]
