# Generated by Django 4.2.2 on 2023-06-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_propertytpe_options_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
