# Generated by Django 4.2.2 on 2023-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_contact_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='New'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.TextField(default='New'),
            preserve_default=False,
        ),
    ]
