# Generated by Django 4.2.2 on 2023-07-20 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_uploaded_image', to='api.property'),
        ),
    ]
